# Generated by Django 2.1.5 on 2019-01-14 08:08


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('NAME', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Animal')),
                ('RACE', models.CharField(choices=[('tamia', 'tamia'), ('hamster', 'hamster'), ('ili pika', 'ili pika'), ('opossum', 'opossum')], max_length=50)),
                ('TYPE', models.CharField(choices=[('rongeur', 'rongeur'), ('marsupial', 'marsupial')], max_length=50)),
                ('ETAT', models.CharField(choices=[('endormi', 'endormi'), ('affamé', 'affamé'), ('repus', 'repus'), ('fatigué', 'fatigué')], max_length=50, verbose_name='ÉTAT')),
                ('LIEU', models.CharField(choices=[('litière', 'litière'), ('mangeoire', 'mangeoire'), ('nid', 'nid')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('equipement', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Équipement')),
                ('DISPO', models.CharField(choices=[('libre', 'libre'), ('occupé', 'occupé')], max_length=50, verbose_name='\tDISPONIBILITÉ')),
            ],
        ),
    ]