# Generated by Django 2.1.5 on 2019-01-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='LIEU',
            field=models.CharField(choices=[('litière', 'litière'), ('mangeoire', 'mangeoire'), ('nid', 'nid'), ('roue', 'roue')], max_length=50),
        ),
    ]